// packages/react-hooks/src/App.jsx
import { memo, useEffect, useReducer } from 'react';
import { render } from 'react-dom';

import { performanceAPI, saveToJSON, generateData, saveUserTimings, dataJSON } from '../../../utils';
import './../../../css/styles.css';

const initialState = { data: [], selected: 0 };
let operationType = 'init';
performance.mark(operationType);

const listReducer = (state, action) => {
  const { data, selected } = state;

  switch (action.type) {
    case 'RUN':
      return { data: generateData(1000), selected: 0 };
    case 'RUN_LOTS':
      return { data: generateData(10000), selected: 0 };
    case 'ADD':
      return { data: data.concat(generateData(1000)), selected };
    case 'UPDATE': {
      const newData = data.slice(0);

      for (let i = 0; i < newData.length; i += 10) {
        const r = newData[i];
        newData[i] = {
          id: r.id,
          firstName: r.firstName + '_updated',
          lastName: r.lastName + '_updated',
          email: 'updated_' + r.email,
          birthday: r.birthday + '_updated'
        };
      }

      return { data: newData, selected };
    }
    case 'CLEAR':
      return { data: [], selected: 0 };
    case 'SWAP_ROWS':
      return data.length > 998
        ? { data: [data[0], data[998], ...data.slice(2, 998), data[1], data[999]], selected }
        : state;
    case 'DELETE': {
      const idx = data.findIndex((d) => d.id === action.id);

      return { data: [...data.slice(0, idx), ...data.slice(idx + 1)], selected };
    }
    case 'SELECT':
      return { data, selected: action.id };
    case 'LOAD':
      return { data: dataJSON, selected: 0 };
    default:
      return state;
  }
};

const Row = memo(
  ({ selected, item, dispatch }) => (
    <tr
      className={selected ? 'success' : ''}
      onClick={() => {
        operationType = 'select';
        performance.mark(operationType);
        return dispatch({ type: 'SELECT', id: item.id });
      }}>
      <td className="col-md-1">{item.id}</td>
      <td className="col-md-4">{item.firstName}</td>
      <td className="col-md-4">{item.lastName}</td>
      <td className="col-md-4">{item.birthday}</td>
      <td className="col-md-4">{item.email}</td>
      <td className="col-md-1">
        <a
          onClick={() => {
            operationType = 'delete';
            performance.mark(operationType);
            return dispatch({ type: 'DELETE', id: item.id });
          }}>
          <span className="fas fa-trash text-danger" aria-hidden="true" />
        </a>
      </td>
      <td className="col-md-6" />
    </tr>
  ),
  (prevProps, nextProps) => prevProps.selected === nextProps.selected && prevProps.item === nextProps.item
);

const Button = ({ id, clicked, title }) => (
  <div className="col-sm-6 smallpad">
    <button type="button" className="btn btn-primary btn-block w-100" id={id} onClick={clicked}>
      {title}
    </button>
  </div>
);

const TestPanel = memo(
  ({ dispatch }) => (
    <div className="jumbotron">
      <div className="row">
        <div className="col-md-2">
          <h1>React Hooks</h1>
        </div>
        <div className="col-md-6">
          <div className="row">
            <Button
              id="create"
              title="Create 1,000 rows"
              clicked={() => {
                operationType = 'create';
                performance.mark(operationType);
                dispatch({ type: 'RUN' });
              }}
            />
            <Button
              id="createLots"
              title="Create 10,000 rows"
              clicked={() => {
                operationType = 'create lots';
                performance.mark(operationType);
                dispatch({ type: 'RUN_LOTS' });
              }}
            />
            <Button
              id="add"
              title="Add 1,000 rows"
              clicked={() => {
                operationType = 'add';
                performance.mark(operationType);
                dispatch({ type: 'ADD' });
              }}
            />
            <Button
              id="update"
              title="Update every 10th row"
              clicked={() => {
                operationType = 'update';
                performance.mark(operationType);
                dispatch({ type: 'UPDATE' });
              }}
            />
            <Button
              id="swapRows"
              title="Swap Rows"
              clicked={() => {
                operationType = 'swap';
                performance.mark(operationType);
                dispatch({ type: 'SWAP_ROWS' });
              }}
            />
            <Button
              id="clear"
              title="Clear"
              clicked={() => {
                operationType = 'clear';
                performance.mark(operationType);
                dispatch({ type: 'CLEAR' });
              }}
            />
            <Button
              id="load"
              title="Load Data"
              clicked={() => {
                operationType = 'load';
                performance.mark(operationType);
                dispatch({ type: 'LOAD' });
              }}
            />
            <Button title="Get Timings" clicked={() => saveUserTimings('react-hooks')} />
          </div>
        </div>
      </div>
    </div>
  ),
  () => <true></true>
);

const App = () => {
  const [{ data, selected }, dispatch] = useReducer(listReducer, initialState);

  useEffect(() => {
    window.addEventListener('load', () => {
      const perf = performanceAPI();
      saveToJSON(perf, 'react.json');
    });
    return window.removeEventListener('load', () => {});
  }, []);

  useEffect(() => {
    setTimeout(() => {
      performance.measure(operationType, operationType);
    });
  });

  return (
    <div className="container" id="#contaiter">
      <TestPanel dispatch={dispatch} />
      <div className="d-flex align-items-center"></div>
      <table className="table table-hover table-striped test-data">
        <tbody>
          {data.map((item) => (
            <Row key={item.id} item={item} selected={selected === item.id} dispatch={dispatch} />
          ))}
        </tbody>
      </table>
      <span className="preloadicon fas fa-trash hover" aria-hidden="true" />
    </div>
  );
};

render(<App />, document.getElementById('App'));

// packages/vue/src/App.vue
<script>
import { performanceAPI, saveToJSON, generateData, saveUserTimings as userTimings, dataJSON } from '../../../utils';

performance.mark('init');

export default {
  data() {
    return {
      operationType: 'init',
      selected: undefined,
      rows: [],
      stopTimer: null
    };
  },
  methods: {
    setRows(update = this.rows.slice()) {
      this.rows = update;
    },

    saveUserTimings() {
      userTimings('vue');
    },

    add() {
      this.operationType = 'add';
      performance.mark(this.operationType);
      this.rows = this.rows.concat(generateData(1000));
    },

    load() {
      this.operationType = 'load';
      performance.mark(this.operationType);
      this.rows = dataJSON;
      this.selected = undefined;
    },

    remove(id) {
      this.operationType = 'delete';
      performance.mark(this.operationType);
      this.rows.splice(
        this.rows.findIndex((d) => d.id === id),
        1
      );
      this.setRows();
    },

    select(id) {
      this.operationType = 'select';
      this.selected = id;
      performance.mark(this.operationType);
    },

    run() {
      this.operationType = 'create';
      performance.mark(this.operationType);
      this.setRows(generateData(1000));
      this.selected = undefined;
    },

    update() {
      this.operationType = 'update';
      performance.mark(this.operationType);
      const _rows = this.rows;
      for (let i = 0; i < _rows.length; i += 10) {
        _rows[i].firstName += '_updated';
        _rows[i].lastName += '_updated';
        _rows[i].email += '_updated';
        _rows[i].birthday += '_updated';
      }
      this.setRows();
    },

    runLots() {
      this.operationType = 'create lots';
      performance.mark(this.operationType);
      this.setRows(generateData(10000));
      this.selected = undefined;
    },

    clear() {
      this.operationType = 'clear';
      performance.mark(this.operationType);
      this.setRows([]);
      this.selected = undefined;
    },

    swapRows() {
      this.operationType = 'swap';
      performance.mark(this.operationType);
      const _rows = this.rows;
      if (_rows.length > 998) {
        const d1 = _rows[1];
        const d998 = _rows[998];
        _rows[1] = d998;
        _rows[998] = d1;
        this.setRows();
      }
    }
  },

  mounted() {
    window.addEventListener('load', () => {
      const perf = performanceAPI();
      saveToJSON(perf, 'vue.json');
    });

    performance.measure(this.operationType, this.operationType);
  },
  updated() {
    setTimeout(() => performance.measure(this.operationType, this.operationType));
  },
  beforeUnmount() {
    window.removeEventListener('load', () => {});
  }
};
</script>

<template>
  <div class="jumbotron">
    <div class="row">
      <div class="col-md-2">
        <h1>
          Vue.js <br />
          v3.2.1
        </h1>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block w-100" id="run" @click="run()">
              Create 1,000 rows
            </button>
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block w-100" id="runlots" @click="runLots()">
              Create 10,000 rows
            </button>
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block w-100" id="add" @click="add()">
              Append 1,000 rows
            </button>
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block w-100" id="update" @click="update()">
              Update every 10th row
            </button>
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block w-100" id="swaprows" @click="swapRows()">
              Swap rows
            </button>
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block w-100" id="clear" @click="clear()">
              Clear rows
            </button>
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block w-100" id="load" @click="load()">
              Load 1,000 rows
            </button>
          </div>
          <div class="col-sm-6 smallpad">
            <button
              type="button"
              class="btn btn-primary btn-block w-100"
              id="saveUserTimings"
              @click="saveUserTimings()"
            >
              Get timings
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <table class="table table-hover table-striped test-data">
    <tbody>
      <tr
        v-for="{ id, firstName, lastName, email, birthday } of rows"
        :key="id"
        :class="{ danger: id === selected }"
        v-memo="[firstName, lastName, email, birthday, id === selected]"
        @click="select(id)"
      >
        <td class="col-md-1">{{ id }}</td>
        <td class="col-md-4">{{ firstName }}</td>
        <td class="col-md-4">{{ lastName }}</td>
        <td class="col-md-4">{{ email }}</td>
        <td class="col-md-4">{{ birthday }}</td>
        <td class="col-md-1">
          <a @click="remove(id)">
            <span class="fas fa-trash text-danger" aria-hidden="true"></span>
          </a>
        </td>
        <td class="col-md-6"></td>
      </tr>
    </tbody>
  </table>
  <span class="preloadicon fas fa-trash" aria-hidden="true"></span>
</template>
